name: Kakao candidates 15:21 KST

on:
  schedule:
    - cron: "21 6 * * 1-5"   # 월~금, UTC 06:21 = KST 15:21
  workflow_dispatch:          # 수동 실행 버튼

jobs:
  send:
    runs-on: ubuntu-latest
    env:
      PYTHONIOENCODING: utf-8
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas python-dotenv

      - name: Run script
        env:
          KAKAO_REST_KEY: ${{ secrets.KAKAO_REST_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
        run: python alerts.py

          fi
